/* eslint-disable import/no-cycle */
/* SETTINGS */
export const CHANGE_LOCALE = 'CHANGE_LOCALE';

/* AUTH */
export const LOGIN_USER = 'LOGIN_USER';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_ERROR = 'LOGIN_USER_ERROR';
export const REGISTER_USER = 'REGISTER_USER';
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_ERROR = 'REGISTER_USER_ERROR';
export const LOGOUT_USER = 'LOGOUT_USER';
export const FORGOT_PASSWORD = 'FORGOT_PASSWORD';
export const FORGOT_PASSWORD_SUCCESS = 'FORGOT_PASSWORD_SUCCESS';
export const FORGOT_PASSWORD_ERROR = 'FORGOT_PASSWORD_ERROR';
export const RESET_PASSWORD = 'RESET_PASSWORD';
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD_ERROR = 'RESET_PASSWORD_ERROR';

/* MENU */
export const MENU_SET_CLASSNAMES = 'MENU_SET_CLASSNAMES';
export const MENU_CONTAINER_ADD_CLASSNAME = 'MENU_CONTAINER_ADD_CLASSNAME';
export const MENU_CLICK_MOBILE_MENU = 'MENU_CLICK_MOBILE_MENU';
export const MENU_CHANGE_DEFAULT_CLASSES = 'MENU_CHANGE_DEFAULT_CLASSES';
export const MENU_CHANGE_HAS_SUB_ITEM_STATUS =
  'MENU_CHANGE_HAS_SUB_ITEM_STATUS';

/* TODOAPP */
export const TODO_GET_LIST = 'TODO_GET_LIST';
export const TODO_GET_LIST_SUCCESS = 'TODO_GET_LIST_SUCCESS';
export const TODO_GET_LIST_ERROR = 'TODO_GET_LIST_ERROR';
export const TODO_GET_LIST_WITH_FILTER = 'TODO_GET_LIST_WITH_FILTER';
export const TODO_GET_LIST_WITH_ORDER = 'TODO_GET_LIST_WITH_ORDER';
export const TODO_GET_LIST_SEARCH = 'TODO_GET_LIST_SEARCH';
export const TODO_ADD_ITEM = 'TODO_ADD_ITEM';
export const TODO_ADD_ITEM_SUCCESS = 'TODO_ADD_ITEM_SUCCESS';
export const TODO_ADD_ITEM_ERROR = 'TODO_ADD_ITEM_ERROR';
export const TODO_SELECTED_ITEMS_CHANGE = 'TODO_SELECTED_ITEMS_CHANGE';

/* ADMINLOCALCOMERCIAL - APP CATEGORIAS */
export const CATEGORIA_ADD = 'CATEGORIA_ADD';
export const CATEGORIA_ADD_SUCCESS = 'CATEGORIA_ADD_SUCCESS';
export const CATEGORIA_DELETE = 'CATEGORIA_DELETE';
export const CATEGORIA_DELETE_SUCESS = 'CATEGORIA_DELETE_SUCESS';
export const CATEGORIA_UPDATE = 'CATEGORIA_UPDATE';
export const CATEGORIA_DELETE_GROUP = 'CATEGORIA_DELETE_GROUP';

/* ADMINLOCALCOMERCIAL - APP PRODUCTOS */
export const PRODUCTO_ADD = 'PRODUCTO_ADD';
export const PRODUCTO_ADD_SUCCESS = 'PRODUCTO_ADD_SUCCESS';
export const PRODUCTO_DELETE = 'PRODUCTO_DELETE';
export const PRODUCTO_UPDATE = 'PRODUCTO_UPDATE';
export const MOSTRAR_PRODUCTOS_CATEGORIA = 'MOSTRAR_PRODUCTOS_CATEGORIA';
export const MOSTRAR_PRODUCTOS_CATEGORIA_SUCCESS =
  'MOSTRAR_PRODUCTOS_CATEGORIA_SUCCESS';

export * from './menu/actions';
export * from './settings/actions';
export * from './auth/actions';
export * from './todo/actions';
